fix for xef with null reference
revosystems/mojito pull request #13
Opened 2024-07-24 14:29 UTC by JordiFL-Revo

Si xef tenia una referencia en null no s'actualitzava.

2024-07-24 14:35 UTC, draude commented on src/Models/PurchaseOrder.php
> +        if(! $update['reference']){
en aquest cas que no hi ha més valors que puguin ser null, ho pots fer amb un array_filter: https://www.php.net/manual/en/function.array-filter.php

2024-07-24 14:35 UTC, draude requested changes
en aquest cas que no hi ha més valors que puguin ser null, ho pots fer amb un array_filter: https://www.php.net/manual/en/function.array-filter.php

2024-07-24 14:57 UTC, draude approved these changes

2024-07-30 08:31 UTC, BadChoice approved these changes

2024-07-30 08:31 UTC, merged